#! /bin/bash

docker build -t containerception . 
docker run -d -t  --privileged --name containerception  containerception
docker exec -it -u root containerception /bin/bash
docker stop containerception
docker rm containerception