#! /bin/bash

docker build -t containerception . 
docker run -d -t  --name containerception  containerception
docker exec -it containerception /bin/bash
docker stop containerception
docker rm containerception